name: playerRiskLevelManager
main: com.tenth.riskManager.RiskManager
version: 1.0
api-version: 1.21
commands:
  riskManager:
    description: Manage players' risk levels and view notifications.
    usage: /riskManager <help|get|set> [playerName] [riskLevel 1-7]
    permission: riskManager.view
permissions:
  riskManager.view:
    description: Get a player's risk level.
    default: op
  riskManager.set:
    description: Set a player's risk level.
    default: op
